"use client"
import { useEffect, useState } from "react"
import Link from "next/link"
import { useRouter } from "next/navigation"

export default function AdminLoginPage(){
  const router=useRouter(); const [username,setUsername]=useState(""); const [password,setPassword]=useState(""); const [loading,setLoading]=useState(false); const [error,setError]=useState("")
  useEffect(()=>{fetch("/api/medicalneeds/admin/auth").then(r=>r.json()).then(x=>{if(x.authenticated)router.replace("/medicalneeds/admin")}).catch(()=>{})},[router])
  async function signIn(e){e.preventDefault();setLoading(true);setError("");try{const r=await fetch("/api/medicalneeds/admin/auth",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username,password})});const data=await r.json();if(!r.ok)throw new Error(data.error||"Unable to sign in.");router.replace("/medicalneeds/admin")}catch(err){setError(err.message)}finally{setLoading(false)}}
  return <main style={styles.page}><div style={styles.card}><Link href="/medicalneeds" style={styles.back}>← Medpact Care</Link><div style={styles.mark}>M</div><div style={styles.eyebrow}>MEDPACT CARE · INTERNAL</div><h1>Welcome back.</h1><p>Sign in once to manage doctors, hospitals, treatments and cost intelligence.</p><form onSubmit={signIn} style={styles.form}><label>Username<input value={username} onChange={e=>setUsername(e.target.value)} autoComplete="username" required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/></label>{error&&<div style={styles.error}>{error}</div>}<button type="submit" disabled={loading} style={styles.button}>{loading?"Signing in…":"Sign in"}</button></form><small style={styles.note}>Medpact internal access only.</small></div></main>
}
const styles={page:{minHeight:"100vh",background:"linear-gradient(135deg,#edf4f0,#f8faf8)",display:"grid",placeItems:"center",padding:20,fontFamily:"Arial,sans-serif",color:"#12201d"},card:{width:"100%",maxWidth:470,background:"#fff",border:"1px solid #dce6e1",borderRadius:26,padding:"34px",boxShadow:"0 25px 80px rgba(18,32,29,.09)"},back:{color:"#49615a",textDecoration:"none",fontSize:13},mark:{width:52,height:52,borderRadius:17,background:"#12201d",color:"#fff",display:"grid",placeItems:"center",fontFamily:"Georgia,serif",fontSize:29,marginTop:42},eyebrow:{color:"#0e7569",fontSize:10,fontWeight:800,letterSpacing:".15em",marginTop:25},form:{display:"grid",gap:16,marginTop:25},label:{display:"grid",gap:7,fontSize:12,fontWeight:700},error:{background:"#fff1f0",color:"#9b3b33",borderRadius:10,padding:11,fontSize:12},button:{border:0,background:"#12201d",color:"#fff",borderRadius:12,padding:"14px 18px",fontWeight:700,cursor:"pointer"},note:{display:"block",color:"#78837f",fontSize:11,marginTop:18}}
