"use client"
import { useEffect,useState } from "react"
import { usePathname,useRouter } from "next/navigation"
import Link from "next/link"

export default function AdminLayout({children}){const pathname=usePathname();const router=useRouter();const isLogin=pathname==="/medicalneeds/admin/login";const [auth,setAuth]=useState(isLogin?true:null)
 useEffect(()=>{if(isLogin){setAuth(true);return}let active=true;fetch('/api/medicalneeds/admin/auth').then(r=>r.json()).then(d=>{if(!active)return;if(d.authenticated)setAuth(true);else{setAuth(false);router.replace('/medicalneeds/admin/login')}}).catch(()=>{if(active){setAuth(false);router.replace('/medicalneeds/admin/login')}});return()=>{active=false}},[isLogin,router])
 if(isLogin)return children
 if(auth===null)return <div style={styles.loading}>Checking Medpact admin session…</div>
 if(!auth)return null
 return <div style={styles.shell}><aside style={styles.sidebar}><Link href="/medicalneeds/admin" style={styles.logo}><span style={styles.logoMark}>M</span><span>Medpact <b>Care</b></span></Link><div style={styles.label}>INTERNAL</div><nav style={styles.nav}><Link href="/medicalneeds/admin" style={styles.navLink}>Overview</Link><Link href="/medicalneeds/admin/doctors" style={styles.navLink}>Doctors</Link><Link href="/medicalneeds/admin/hospitals" style={styles.navLink}>Hospitals</Link><Link href="/medicalneeds/admin/treatments" style={styles.navLink}>Treatments & Costs</Link></nav><div style={styles.bottom}><Link href="/medicalneeds" style={styles.publicLink}>← Public website</Link><button style={styles.signout} onClick={async()=>{await fetch('/api/medicalneeds/admin/auth',{method:'DELETE'});router.replace('/medicalneeds/admin/login')}}>Sign out</button></div></aside><div style={styles.content}>{children}</div></div>}
const styles={shell:{minHeight:'100vh',background:'#f5f7f5',color:'#12201d',fontFamily:'Arial,sans-serif',display:'flex'},sidebar:{width:245,background:'#10201d',color:'#fff',minHeight:'100vh',padding:'26px 18px',display:'flex',flexDirection:'column',position:'sticky',top:0,height:'100vh'},logo:{display:'flex',alignItems:'center',gap:10,color:'#fff',textDecoration:'none',fontWeight:700,fontSize:16},logoMark:{width:35,height:35,borderRadius:11,background:'#fff',color:'#10201d',display:'grid',placeItems:'center',fontFamily:'Georgia,serif',fontSize:21},label:{fontSize:9,letterSpacing:'.18em',color:'#8fa39d',fontWeight:800,margin:'38px 10px 10px'},nav:{display:'grid',gap:6},navLink:{color:'#b9c7c2',textDecoration:'none',padding:'12px',borderRadius:11,fontSize:13,fontWeight:600},bottom:{marginTop:'auto',display:'grid',gap:8},publicLink:{color:'#b9c7c2',textDecoration:'none',padding:'10px 12px',fontSize:12},signout:{border:'1px solid #3b5750',background:'transparent',color:'#fff',borderRadius:10,padding:'10px 12px',cursor:'pointer'},content:{flex:1,minWidth:0},loading:{minHeight:'100vh',display:'grid',placeItems:'center',background:'#f5f7f5',color:'#52625d',fontFamily:'Arial,sans-serif'}}
